- name: Scratch
  hosts: all
  become: yes
  become_method: sudo

  vars_files:
    - vars/main.yml

  roles:
    - { role: role_common, tags: "role_common"}  
    - { role: role_cloud, tags: "role_cloud"}  
    - { role: role_node.js, tags: "role_node.js"}
    - { role: role_nginx, tags: "role_nginx"}     
    - { role: scratch-gui, tags: "scratch-gui"}
    - { role: role_preend, tags: "role_preend"}  
    - { role: role_end, tags: "role_end"}  

